### ISSUE TITLE
how to train the  Quadruped Joint Predictor

### ISSUE THREAD

**Issue by buaaswf** [benjiebob/SMALify#12]
Hi @benjiebob ,
I try to apply this to other Quadruped animals, could you please show me the details about how to train the Quadruped Joint Predictor?
Thanks 

yours
Wenfeng

**Comment by benjiebob** [comment]
Automatic prediction of quadruped joints is not yet included in this library. The basic idea is to create a synthetic set of SMAL quadruped models and train hourglass network to predict the joints. 

A similar idea (that relies on few keypoint annotations) is available here [SMALST](https://github.com/silviazuffi/smalst) and shown on zebra.

**Comment by benjiebob** [comment]
Going to close for now.
