### ISSUE TITLE
badja_extra_videos.zip doesn't seem to exist anymore

### ISSUE THREAD

**Issue by nightfarrow** [benjiebob/SMALify#21]
It appears that `badja_extra_videos.zip` doesn't seem to exist anymore.

I tried running `wget http://mi.eng.cam.ac.uk/~bjb56/datasets/badja_extra_videos.zip` and got connection timed out.

Manually visiting `http://mi.eng.cam.ac.uk/~bjb56/datasets/badja_extra_videos.zip` just loads forever.

 is there a working mirror of these videos? also, is it necessary to use these particular videos, or can any animal videos like from YouTube be used? (Newbie here)

**Comment by benjiebob** [comment]
Ah yes -- it looks like our Cambridge hosting server is down. I've created a [mirror](https://drive.google.com/file/d/1ad1BLmzyOp_g3BfpE2yklNI-E1b8y4gy/view?usp=sharing) which you can use. 

You can use any videos you like -- you'll need to generate segementations and click keypoints, to generate equivalent input files to the examples. Look at my README.md page for some tips (it's not quite complete but should get you started).
