### ISSUE TITLE
http://mi.eng.cam.ac.uk/~bjb56/datasets/badja_extra_videos.zip    NOT FOUND

### ISSUE THREAD

**Issue by shirleyanan** [benjiebob/SMALify#29]
cd data/BADJA
wget http://mi.eng.cam.ac.uk/~bjb56/datasets/badja_extra_videos.zip
unzip badja_extra_videos.zip
   this link is not found ,could you have the other one for me to download badja_extra_videos.zip?Thanks!

**Comment by mshooter** [comment]
you can download these here https://github.com/benjiebob/BADJA

**Comment by benjiebob** [comment]
Thanks @mshooter. I've updated the README of this repo with the updated [Google Drive link](https://drive.google.com/file/d/1ad1BLmzyOp_g3BfpE2yklNI-E1b8y4gy/view?usp=sharing)
