### ISSUE TITLE
subtle confusion on what needs to be downloaded from SMPL website

### ISSUE THREAD

**Issue by monajalal** [benjiebob/SMALify#3]
Hi Benjamin,

Awesome code repo and great documentation so far.

However, since there is a bunch of downloadable things from SMPL website, would be best to add what needs to be downloaded.

Also, I guess smal folder inside data was missing in the repo (I did mkdir smal -- telling it since I saw you had folder for other things).

![smpl_download](https://user-images.githubusercontent.com/1892917/94761312-b1424f00-0372-11eb-8bc8-dc02a95a3651.png)

For example, 

Is this the correct structure?
![tree_smalify](https://user-images.githubusercontent.com/1892917/94769462-181a3500-0380-11eb-8b39-d830bb7170be.png)

**Comment by monajalal** [comment]
the smpl after extraction has these folders:
smpl$ ls
total 28K
-rw-r--r-- 1 mona mona  535 Dec  9  2015 __init__.py
drwxr-xr-x 2 mona mona 4.0K Dec 11  2015 models
-rw-r--r-- 1 mona mona 6.1K Dec 11  2015 .DS_Store
drwxr-xr-x 3 mona mona 4.0K Dec 12  2015 smpl_webuser
drwxr-xr-x 4 mona mona 4.0K Dec 12  2015 .
drwxrwxr-x 5 mona mona 4.0K Oct  1 00:49 ..


you need to move smpl_webuser to smal_model folder

**Comment by benjiebob** [comment]
Yep, that's right. As detailed in the README, important to move smpl_webuser to the smal_folder. If it helps, this is the tree under smpl_webuser:
```
(/hpc/user_apps/bjb10042/smalify) [bjb10042@uptus095-4 SMALify]$ tree smal_model/smpl_webuser/smal_model/smpl_webuser/
├── hello_world
│   ├── hello_smpl.py
│   └── render_smpl.py
├── __init__.py
├── lbs.py
├── LICENSE.txt
├── posemapper.py
├── __pycache__
│   ├── __init__.cpython-36.pyc
│   ├── lbs.cpython-36.pyc
│   ├── posemapper.cpython-36.pyc
│   ├── serialization.cpython-36.pyc
│   └── verts.cpython-36.pyc
├── README.txt
├── serialization.py
└── verts.py

2 directories, 14 files
```

**Comment by benjiebob** [comment]
https://github.com/benjiebob/SMALify/issues/6#issuecomment-702257845

**Comment by benjiebob** [comment]
SMPL dependency is now removed. https://github.com/benjiebob/SMALify/issues/6#issuecomment-702278462
