### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by buaaswf** [benjiebob/SMALify#9]
Dear @benjiebob ,
Could you please give me more details about the versions of you dependencies, such as python, torch, ...etc.
I use python 3.6 and torch1.6, which leads to the encoding error. when I load the smalst models
`    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 0: ordinal not in range(128)`

Please help me.
Thanks

**Comment by monajalal** [comment]
Here's a solution for your error 

https://github.com/benjiebob/SMALify/issues/6

**Comment by benjiebob** [comment]
Thanks @monajalal. @buaaswf I will add a requirements.txt to the repo for folks to refer to.

**Comment by benjiebob** [comment]
See requirements.txt now in the master branch.
